In [36]:
import pandas as pd
import numpy as np

In [37]:
fake = pd.read_csv("./Fake.csv")
real = pd.read_csv("./True.csv")

In [38]:
fake["target"] = 0
fake.head()

,title,text,subject,date,target
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [39]:
real["target"] = 1

In [40]:
fake.shape,real.shape

((23481, 5), (21417, 5))

In [41]:
merged = pd.concat([real,fake],axis=0)
merged.head()

,title,text,subject,date,target
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [42]:
merged = merged.drop(["subject","date","title"],axis=1)

In [43]:
merged.isnull().sum()

text      0
target    0
dtype: int64

In [44]:
#suffleling the data
merged = merged.sample(frac=1)
merged

                                                    text  target
19892  We re just wondering if the state of MN has ev...       0
15746  BRUSSELS (Reuters) - The European Union vowed ...       1
4412   It s become a weekly ritual: Trump goes throug...       0
16286  John Kerry gave a long-winded speech today cla...       0
18030  BEIRUT/DUBAI (Reuters) - Iran warned the Unite...       1
...                                                  ...     ...
10670  (Reuters) - The nominating contests that will ...       1
5565   SACRAMENTO, Calif. (Reuters) - The prospect of...       1
1489   WASHINGTON (Reuters) - President Donald Trump’...       1
9537   LONDON (Reuters) - Presumptive U.S. Republican...       1
16012  BEIRUT (Reuters) - With Islamic State near def...       1

[44898 rows x 2 columns]

In [45]:
merged.reset_index(inplace = True)#resetting the index as it was suffled before
merged.drop(["index"],axis=1,inplace=True)

In [46]:
merged.head()

                                                text  target
0  We re just wondering if the state of MN has ev...       0
1  BRUSSELS (Reuters) - The European Union vowed ...       1
2  It s become a weekly ritual: Trump goes throug...       0
3  John Kerry gave a long-winded speech today cla...       0
4  BEIRUT/DUBAI (Reuters) - Iran warned the Unite...       1

In [48]:
X = merged["text"]
y = merged["target"]

In [58]:
#reduction of noise like 
from sklearn.feature_extraction.text import TfidfVectorizer

vector = TfidfVectorizer(
    stop_words="english",
    lowercase=True
)

X_reduce = vector.fit_transform(X)

In [59]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X_reduce,y,random_state=10,test_size=0.2)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6881046 stored elements and shape (44898, 121690)>

In [ ]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(X_train,y_train)

LogisticRegression()

In [63]:
LR.score(X_train,y_train)

0.9918425302076953

In [64]:
c = "Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t even allow him to rise above the gutter long enough to wish the American citizens a happy new year!  Bishop Talbert Swan (@TalbertSwan) December 31, 2017no one likes you  Calvin (@calvinstowell) December 31, 2017Your impeachment would make 2018 a great year for America, but I ll also accept regaining control of Congress.  Miranda Yaver (@mirandayaver) December 31, 2017Do you hear yourself talk? When you have to include that many people that hate you you have to "

array([0])